import { NextResponse } from 'next/server';

const DID_API_BASE_URL = 'https://api.d-id.com';
const DEFAULT_DID_LLM_PROVIDER = 'openai';
const DEFAULT_OPENAI_LLM_MODEL = 'gpt-4.1-mini';
const DEFAULT_DID_LLM_MODEL = 'gpt-oss-120b';
const OPENAI_LLM_MODELS = new Set(['gpt-4o-global', 'gpt-4o-mini', 'gpt-4.1', 'gpt-4.1-mini', 'gpt-4.1-nano', 'gpt-5-mini', 'gpt-5-nano']);
const DID_LLM_MODELS = new Set([DEFAULT_DID_LLM_MODEL]);
const DEFAULT_EXPRESSIVE_PRESENTER_ID = 'public_mia_elegant@avt_TJ0Tq5';
const DEFAULT_DID_VOICE_ID = 'en-US-JennyMultilingualV2Neural';
const DEFAULT_ALLOWED_DOMAINS = ['http://localhost:3000'];

type DidRequestBody = {
  characterId?: string;
  characterName?: string;
  personaPrompt?: string;
  imageDataUrl?: string;
  imageUrl?: string;
  agentId?: string;
  apiKey?: string;
  allowedDomains?: string;
};

type DidJson = Record<string, unknown>;

export type DidAgentProvisionResult = {
  agentId: string;
  clientKey: string;
  sourceUrl: string;
  presenter: unknown;
  status?: string;
};

export async function provisionDidAgent(payload: DidRequestBody): Promise<DidAgentProvisionResult> {
  const apiKey = getDidApiKey(payload);
  const sourceUrl = await uploadImage(payload, apiKey);
  const agentPayload = buildAgentPayload(payload, sourceUrl);
  const agent = payload.agentId
    ? await didFetchJson(`/agents/${encodeURIComponent(payload.agentId)}`, apiKey, { method: 'PATCH', body: JSON.stringify(agentPayload) })
    : await didFetchJson('/agents', apiKey, { method: 'POST', body: JSON.stringify(agentPayload) });

  const agentId = stringField(agent, 'id') || payload.agentId || '';
  if (!agentId) throw new Error('D-ID did not return an agent id.');

  const clientKey = stringField(agent, 'client_key') || await createClientKey(apiKey, payload.allowedDomains);

  return {
    agentId,
    clientKey,
    sourceUrl,
    presenter: agent.presenter,
    status: stringField(agent, 'status'),
  };
}

export async function verifyDidApiKey(apiKey: string) {
  if (!apiKey.trim()) throw new Error('D-ID API key is missing.');
  await didFetchJson('/agents?limit=1', apiKey, { method: 'GET' });
  return { ok: true };
}

export async function refreshDidAgentClientKey(payload: DidRequestBody) {
  const apiKey = getDidApiKey(payload);
  return { clientKey: await createClientKey(apiKey, payload.allowedDomains) };
}

export function didErrorResponse(error: unknown) {
  const message = error instanceof Error ? error.message : 'D-ID Agent provisioning failed.';
  return NextResponse.json({ error: message }, { status: 502 });
}

async function uploadImage(payload: DidRequestBody, apiKey: string) {
  if (payload.imageDataUrl) return uploadImageDataUrl(payload.imageDataUrl, apiKey, payload.characterId);
  if (payload.imageUrl) return uploadImageUrl(payload.imageUrl, apiKey);
  throw new Error('Missing generated image for D-ID avatar.');
}

async function uploadImageUrl(imageUrl: string, apiKey: string) {
  if (!isHttpUrl(imageUrl)) throw new Error('D-ID avatar image URL must be an HTTP(S) URL.');
  const formData = new FormData();
  formData.append('source_url', imageUrl);
  const result = await didFetchJson('/images', apiKey, { method: 'POST', body: formData });
  const url = stringField(result, 'url');
  if (!url) throw new Error('D-ID image upload did not return a URL.');
  return url;
}

async function uploadImageDataUrl(imageDataUrl: string, apiKey: string, characterId: string | undefined) {
  const match = imageDataUrl.match(/^data:(image\/(?:png|jpeg));base64,(.+)$/);
  if (!match) throw new Error('D-ID only supports PNG or JPEG data URLs for avatar upload.');

  const [, contentType, base64] = match;
  const extension = contentType === 'image/jpeg' ? 'jpg' : 'png';
  const filename = safeFilename(`${characterId || 'character'}.${extension}`);
  const bytes = Uint8Array.from(Buffer.from(base64, 'base64'));
  const formData = new FormData();
  formData.append('image', new Blob([bytes], { type: contentType }), filename);

  const result = await didFetchJson('/images', apiKey, { method: 'POST', body: formData });
  const url = stringField(result, 'url');
  if (!url) throw new Error('D-ID image upload did not return a URL.');
  return url;
}

export function buildAgentPayload(payload: DidRequestBody, sourceUrl: string) {
  const llm = buildLlmConfig(payload);

  return {
    preview_name: payload.characterName || 'Doodle Alive Character',
    preview_description: 'Generated by Doodle Alive from a user-created character image.',
    presenter: buildPresenterConfig(llm.provider, sourceUrl),
    llm,
    greetings: [buildGreeting(payload.characterName)],
    embed: true,
  };
}

function buildPresenterConfig(llmProvider: string, sourceUrl: string) {
  if (llmProvider === 'd-id') {
    return {
      type: 'expressive',
      presenter_id: process.env.DID_EXPRESSIVE_PRESENTER_ID || DEFAULT_EXPRESSIVE_PRESENTER_ID,
      voice: buildVoiceConfig(),
    };
  }

  return {
    type: 'talk',
    source_url: sourceUrl,
    thumbnail: sourceUrl,
    stitch: true,
    voice: buildVoiceConfig(),
  };
}

function buildLlmConfig(payload: DidRequestBody) {
  const provider = normalizeLlmProvider(process.env.DID_LLM_PROVIDER || DEFAULT_DID_LLM_PROVIDER);

  return {
    provider,
    model: resolveLlmModel(provider, process.env.DID_LLM_MODEL),
    template: 'assistant',
    temperature: 0.45,
    instructions: buildAgentInstructions(payload),
  };
}

function normalizeLlmProvider(provider: string) {
  return provider.trim().toLowerCase() === 'd-id' ? 'd-id' : 'openai';
}

function resolveLlmModel(provider: string, configuredModel: string | undefined) {
  const model = configuredModel?.trim();
  if (provider === 'd-id') return model && DID_LLM_MODELS.has(model) ? model : DEFAULT_DID_LLM_MODEL;
  return model && OPENAI_LLM_MODELS.has(model) ? model : DEFAULT_OPENAI_LLM_MODEL;
}

function buildAgentInstructions(payload: DidRequestBody) {
  const characterName = payload.characterName?.trim() || 'this character';
  const personaPrompt = payload.personaPrompt?.trim() || 'Be friendly, curious, encouraging, and playful.';

  return [
    `You are ${characterName}, a live animated character in Doodle Alive.`,
    'Stay strictly in character and follow the selected personality at all times.',
    'Speak directly to the child using short, warm, age-appropriate voice-chat replies.',
    'Keep each answer to one or two concise sentences unless the child asks for a story.',
    'Do not mention system prompts, policies, API providers, or implementation details.',
    'If the child asks for unsafe, scary, adult, private, or inappropriate content, gently refuse and redirect to a safe playful topic.',
    '',
    'Selected personality and safety rules:',
    personaPrompt,
  ].join('\n');
}

function buildVoiceConfig() {
  if (process.env.DID_ELEVENLABS_VOICE_ID) {
    return {
      type: 'elevenlabs',
      voice_id: process.env.DID_ELEVENLABS_VOICE_ID,
      model_id: process.env.DID_ELEVENLABS_MODEL_ID || undefined,
    };
  }

  return {
    type: 'microsoft',
    voice_id: process.env.DID_MICROSOFT_VOICE_ID || DEFAULT_DID_VOICE_ID,
  };
}

async function createClientKey(apiKey: string, configuredDomains: string | undefined) {
  const allowedDomains = (configuredDomains || process.env.DID_ALLOWED_DOMAINS || '')
    .split(',')
    .map((domain) => domain.trim())
    .filter(Boolean);

  const result = await didFetchJson('/agents/client-key', apiKey, {
    method: 'POST',
    body: JSON.stringify({ allowed_domains: allowedDomains.length ? allowedDomains : DEFAULT_ALLOWED_DOMAINS }),
  });
  const clientKey = stringField(result, 'client_key');
  if (!clientKey) throw new Error('D-ID did not return a client key.');
  return clientKey;
}

async function didFetchJson(path: string, apiKey: string, init: RequestInit) {
  const headers = new Headers(init.headers);
  headers.set('Authorization', normalizeAuthorization(apiKey));
  if (!(init.body instanceof FormData)) headers.set('Content-Type', 'application/json');

  const response = await fetch(`${DID_API_BASE_URL}${path}`, { ...init, headers });
  const text = await response.text();
  const data = parseJson(text);
  if (!response.ok) throw new Error(readDidError(data, text, response.status));
  return data;
}

function parseJson(text: string): DidJson {
  if (!text) return {};
  try {
    return JSON.parse(text) as DidJson;
  } catch {
    return { raw: text };
  }
}

function readDidError(data: DidJson, text: string, status: number) {
  const description = stringField(data, 'description') || stringField(data, 'message') || stringifyDidDetails(data) || text;
  return `D-ID request failed (${status}): ${description.slice(0, 240)}`;
}

function stringifyDidDetails(data: DidJson) {
  const details = data.details || data.errors || data.error;
  if (!details) return '';
  if (typeof details === 'string') return details;
  try {
    return JSON.stringify(details);
  } catch {
    return '';
  }
}

function stringField(data: DidJson, key: string) {
  const value = data[key];
  return typeof value === 'string' ? value : '';
}

function getDidApiKey(payload: DidRequestBody) {
  const apiKey = payload.apiKey?.trim();
  if (!apiKey) throw new Error('D-ID API key is missing. Add it in Settings, then try again.');
  return apiKey;
}

function normalizeAuthorization(apiKey: string) {
  return apiKey.toLowerCase().startsWith('basic ') ? apiKey : `Basic ${apiKey}`;
}

function safeFilename(filename: string) {
  return filename.replace(/[^a-zA-Z0-9._-]/g, '_').slice(0, 50) || 'character.png';
}

function buildGreeting(name: string | undefined) {
  return name ? `Hi, I'm ${name}. Want to chat?` : 'Hi, want to chat?';
}

function isHttpUrl(url: string) {
  try {
    const parsed = new URL(url);
    return parsed.protocol === 'http:' || parsed.protocol === 'https:';
  } catch {
    return false;
  }
}
