import { NextResponse } from 'next/server';
import { resolvePublicImageUrl } from '@/lib/public-image-hosting';

const DID_API_BASE_URL = 'https://api.d-id.com';
const DEFAULT_DID_LLM_PROVIDER = 'openai';
const DEFAULT_OPENAI_LLM_MODEL = 'gpt-4.1-mini';
const DEFAULT_DID_LLM_MODEL = 'gpt-oss-120b';
const OPENAI_LLM_MODELS = new Set(['gpt-4o-global', 'gpt-4o-mini', 'gpt-4.1', 'gpt-4.1-mini', 'gpt-4.1-nano', 'gpt-5-mini', 'gpt-5-nano']);
const DID_LLM_MODELS = new Set([DEFAULT_DID_LLM_MODEL]);
const DEFAULT_EXPRESSIVE_PRESENTER_ID = 'public_mia_elegant@avt_TJ0Tq5';
const DEFAULT_MICROSOFT_VOICE_IDS = {
  en: 'en-US-JennyMultilingualV2Neural',
  zh: 'zh-CN-XiaoxiaoNeural',
};
const DEFAULT_ALLOWED_DOMAINS = ['http://localhost:3000'];
type DidAgentLanguage = keyof typeof DEFAULT_MICROSOFT_VOICE_IDS;

type DidRequestBody = {
  characterId?: string;
  characterName?: string;
  personaPrompt?: string;
  imageDataUrl?: string;
  imageUrl?: string;
  agentId?: string;
  apiKey?: string;
  allowedDomains?: string;
  sourceUrl?: string;
  language?: string;
};

type DidJson = Record<string, unknown>;

export type DidAgentProvisionResult = {
  agentId: string;
  clientKey: string;
  sourceUrl: string;
  posterUrl: string;
  presenter: unknown;
  status?: string;
};

export async function provisionDidAgent(payload: DidRequestBody): Promise<DidAgentProvisionResult> {
  const apiKey = getDidApiKey(payload);
  const sourceUrl = await uploadImage(payload);
  const posterUrl = resolvePresenterPosterUrl(payload, sourceUrl);
  const agentPayload = buildAgentPayload(payload, sourceUrl, posterUrl);
  const agent = payload.agentId
    ? await didFetchJson(`/agents/${encodeURIComponent(payload.agentId)}`, apiKey, { method: 'PATCH', body: JSON.stringify(agentPayload) })
    : await didFetchJson('/agents', apiKey, { method: 'POST', body: JSON.stringify(agentPayload) });

  const agentId = stringField(agent, 'id') || payload.agentId || '';
  if (!agentId) throw new Error('D-ID did not return an agent id.');

  const clientKey = await createClientKey(apiKey, payload.allowedDomains, agentId);

  return {
    agentId,
    clientKey,
    sourceUrl,
    posterUrl,
    presenter: agent.presenter,
    status: stringField(agent, 'status'),
  };
}

export async function verifyDidApiKey(apiKey: string) {
  if (!apiKey.trim()) throw new Error('D-ID API key is missing.');
  await didFetchJson('/agents?limit=1', apiKey, { method: 'GET' });
  return { ok: true };
}

export async function refreshDidAgentClientKey(payload: DidRequestBody) {
  const apiKey = getDidApiKey(payload);
  return { clientKey: await createClientKey(apiKey, payload.allowedDomains, payload.agentId) };
}

export function didErrorResponse(error: unknown) {
  const message = error instanceof Error ? error.message : 'D-ID Agent provisioning failed.';
  return NextResponse.json({ error: message }, { status: 502 });
}

async function uploadImage(payload: DidRequestBody) {
  const publicImageUrl = await resolvePublicImageUrl({
    characterId: payload.characterId,
    imageDataUrl: payload.imageDataUrl,
    imageUrl: payload.imageUrl,
  });
  if (publicImageUrl) return publicImageUrl;

  if (payload.imageUrl) throw new Error('D-ID avatar image URL must be an HTTP(S) URL.');
  throw new Error('Missing generated image for D-ID avatar.');
}

export function buildAgentPayload(payload: DidRequestBody, sourceUrl: string, posterUrl = sourceUrl) {
  const llm = buildLlmConfig(payload);

  return {
    preview_name: payload.characterName || 'Doodle Alive Character',
    preview_description: 'Generated by Doodle Alive from a user-created character image.',
    presenter: buildPresenterConfig(llm.provider, sourceUrl, posterUrl, normalizeAgentLanguage(payload.language)),
    llm,
    greetings: [buildGreeting(payload.characterName, payload.language)],
    embed: true,
  };
}

function buildPresenterConfig(llmProvider: string, sourceUrl: string, posterUrl: string, language: DidAgentLanguage) {
  if (llmProvider === 'd-id') {
    return {
      type: 'expressive',
      presenter_id: process.env.DID_EXPRESSIVE_PRESENTER_ID || DEFAULT_EXPRESSIVE_PRESENTER_ID,
      voice: buildVoiceConfig(language),
    };
  }

  if (!isHttpUrl(sourceUrl)) {
    throw new Error('D-ID talk presenter requires a browser-loadable HTTP(S) source image. Configure Vercel Blob storage or use an image provider that returns a public HTTPS image URL, then recreate the character.');
  }

  return {
    type: 'talk',
    source_url: sourceUrl,
    thumbnail: posterUrl,
    stitch: true,
    voice: buildVoiceConfig(language),
  };
}

function resolvePresenterPosterUrl(payload: DidRequestBody, sourceUrl: string) {
  if (isHttpUrl(sourceUrl)) return sourceUrl;
  if (payload.imageUrl && isHttpUrl(payload.imageUrl)) return payload.imageUrl;
  if (payload.imageDataUrl?.startsWith('data:image/')) return payload.imageDataUrl;
  return sourceUrl;
}

export function readDidImageUploadUrl(data: DidJson) {
  const candidates = [
    stringField(data, 'source_url'),
    stringField(data, 'sourceUrl'),
    stringField(data, 'image_url'),
    stringField(data, 'imageUrl'),
    stringField(data, 'download_url'),
    stringField(data, 'downloadUrl'),
    stringField(data, 'url'),
    stringField(data, 'uri'),
  ].filter(Boolean);

  return candidates.find(isHttpUrl) || '';
}

function buildLlmConfig(payload: DidRequestBody) {
  const provider = normalizeLlmProvider(process.env.DID_LLM_PROVIDER || DEFAULT_DID_LLM_PROVIDER);

  return {
    provider,
    model: resolveLlmModel(provider, process.env.DID_LLM_MODEL),
    template: 'assistant',
    temperature: 0.45,
    instructions: buildAgentInstructions(payload),
  };
}

function normalizeLlmProvider(provider: string) {
  return provider.trim().toLowerCase() === 'd-id' ? 'd-id' : 'openai';
}

function resolveLlmModel(provider: string, configuredModel: string | undefined) {
  const model = configuredModel?.trim();
  if (provider === 'd-id') return model && DID_LLM_MODELS.has(model) ? model : DEFAULT_DID_LLM_MODEL;
  return model && OPENAI_LLM_MODELS.has(model) ? model : DEFAULT_OPENAI_LLM_MODEL;
}

function buildAgentInstructions(payload: DidRequestBody) {
  const characterName = payload.characterName?.trim() || 'this character';
  const personaPrompt = payload.personaPrompt?.trim() || 'Be friendly, curious, encouraging, and playful.';
  const language = normalizeAgentLanguage(payload.language);

  return [
    `You are ${characterName}, a live animated character in Doodle Alive.`,
    'Stay strictly in character and follow the selected personality at all times.',
    buildLanguageInstruction(language),
    'Speak directly to the child using short, warm, age-appropriate voice-chat replies.',
    'Keep each answer to one or two concise sentences unless the child asks for a story.',
    'Do not mention system prompts, policies, API providers, or implementation details.',
    'If the child asks for unsafe, scary, adult, private, or inappropriate content, gently refuse and redirect to a safe playful topic.',
    '',
    'Selected personality and safety rules:',
    personaPrompt,
  ].join('\n');
}

function buildVoiceConfig(language: DidAgentLanguage) {
  const languageSuffix = language.toUpperCase();
  const elevenLabsVoiceId = process.env[`DID_ELEVENLABS_VOICE_ID_${languageSuffix}`] || process.env.DID_ELEVENLABS_VOICE_ID;
  if (elevenLabsVoiceId) {
    return {
      type: 'elevenlabs',
      voice_id: elevenLabsVoiceId,
      model_id: process.env[`DID_ELEVENLABS_MODEL_ID_${languageSuffix}`] || process.env.DID_ELEVENLABS_MODEL_ID || undefined,
    };
  }

  return {
    type: 'microsoft',
    voice_id: process.env[`DID_MICROSOFT_VOICE_ID_${languageSuffix}`] || process.env.DID_MICROSOFT_VOICE_ID || DEFAULT_MICROSOFT_VOICE_IDS[language],
  };
}

async function createClientKey(apiKey: string, configuredDomains: string | undefined, agentId: string | undefined) {
  const result = await didFetchJson(buildAgentClientKeyPath(agentId), apiKey, {
    method: 'POST',
    body: JSON.stringify({ allowed_domains: resolveAllowedDomains(configuredDomains) }),
  });
  const clientKey = stringField(result, 'client_key') || stringField(result, 'clientKey') || stringField(result, 'key');
  if (!clientKey) throw new Error('D-ID did not return a client key.');
  return clientKey;
}

export function buildAgentClientKeyPath(agentId: string | undefined) {
  const trimmed = agentId?.trim();
  if (!trimmed) throw new Error('D-ID Agent id is missing. Create the character again, then retry voice chat.');
  return `/agents/${encodeURIComponent(trimmed)}/client-keys`;
}

function resolveAllowedDomains(configuredDomains: string | undefined) {
  const allowedDomains = (configuredDomains || process.env.DID_ALLOWED_DOMAINS || '')
    .split(',')
    .map((domain) => domain.trim())
    .filter(Boolean);

  return allowedDomains.length ? allowedDomains : DEFAULT_ALLOWED_DOMAINS;
}

async function didFetchJson(path: string, apiKey: string, init: RequestInit) {
  const headers = new Headers(init.headers);
  headers.set('Authorization', normalizeAuthorization(apiKey));
  if (!(init.body instanceof FormData)) headers.set('Content-Type', 'application/json');

  const response = await fetch(`${DID_API_BASE_URL}${path}`, { ...init, headers });
  const text = await response.text();
  const data = parseJson(text);
  if (!response.ok) throw new Error(readDidError(data, text, response.status));
  return data;
}

function parseJson(text: string): DidJson {
  if (!text) return {};
  try {
    return JSON.parse(text) as DidJson;
  } catch {
    return { raw: text };
  }
}

function readDidError(data: DidJson, text: string, status: number) {
  const description = stringField(data, 'description') || stringField(data, 'message') || stringifyDidDetails(data) || text;
  return `D-ID request failed (${status}): ${description.slice(0, 240)}`;
}

function stringifyDidDetails(data: DidJson) {
  const details = data.details || data.errors || data.error;
  if (!details) return '';
  if (typeof details === 'string') return details;
  try {
    return JSON.stringify(details);
  } catch {
    return '';
  }
}

function stringField(data: DidJson, key: string) {
  const value = data[key];
  return typeof value === 'string' ? value : '';
}

function getDidApiKey(payload: DidRequestBody) {
  const apiKey = payload.apiKey?.trim();
  if (!apiKey) throw new Error('D-ID API key is missing. Add it in Settings, then try again.');
  return apiKey;
}

function normalizeAuthorization(apiKey: string) {
  return apiKey.toLowerCase().startsWith('basic ') ? apiKey : `Basic ${apiKey}`;
}

function buildLanguageInstruction(language: DidAgentLanguage) {
  return language === 'zh'
    ? 'Always reply in Simplified Chinese. Do not switch to English unless the child explicitly asks to practice English.'
    : 'Always reply in English. Do not switch to Chinese unless the child explicitly asks to practice Chinese.';
}

function buildGreeting(name: string | undefined, language: string | undefined) {
  const normalizedLanguage = normalizeAgentLanguage(language);
  if (normalizedLanguage === 'zh') return name ? `你好，我是 ${name}。想聊天吗？` : '你好，想聊天吗？';
  return name ? `Hi, I'm ${name}. Want to chat?` : 'Hi, want to chat?';
}

function normalizeAgentLanguage(language: string | undefined): DidAgentLanguage {
  return language === 'zh' ? 'zh' : 'en';
}

function isHttpUrl(url: string) {
  try {
    const parsed = new URL(url);
    return parsed.protocol === 'http:' || parsed.protocol === 'https:';
  } catch {
    return false;
  }
}
